#!/bin/bash

# Install Manuel's mirrorlist.

DIE() {
    echo "Error: $1" >&2
    exit 1
}

Sha512() {
    source PKGBUILD
    echo "${sha512sums[0]}  $pkgname" | sha512sum -c >/dev/null || DIE "checksum failed."
    echo "OK"
}

Main()
{
    local url=https://github.com/manuel-192/m-more/raw/master/PKGBUILDs/mirrorlist-m
    local list=/etc/pacman.d/mirrorlist-m
    local conf=/etc/pacman.conf
    local cmds=(":")           # does nothing!
    local key=A1F1B5187D25904B
    local repo repos=(m-m m-more)
    local tmpdir=$(mktemp -d)
    local sha512

    # command to create /etc/pacman.d/mirrorlist-m
    if [ ! -r $list ] ; then
        pushd $tmpdir >/dev/null
        wget -q -O mirrorlist-m $url/mirrorlist-m || DIE "fetching mirrorlist failed."
        wget -q -O PKGBUILD     $url/PKGBUILD     || DIE "fetching PKGBUILD failed."
        test "$(Sha512)" = "OK"                   || DIE "mirrorlist checksum failed."
        popd >/dev/null
        cmds+=("; cp $tmpdir/mirrorlist-m $list")
    fi

    # adds Manuel's repos to /etc/pacman.conf
    for repo in "${repos[@]}" ; do
        grep "^\[$repo\]$" $conf >/dev/null || {
            cmds+=("; echo '' >> $conf")
            cmds+=("; echo '[$repo]' >> $conf")
            cmds+=("; echo 'Include = $list' >> $conf")
        }
    done

    # adds proper gpg key
    if [ -z "$(pacman-key --list-sigs 2>/dev/null | grep -w $key)" ] ; then
        cmds+=("; pacman-key --recv-keys $key")
        cmds+=("; pacman-key --lsign-key $key")
    fi

    # run commands if there are any
    if [ ${#cmds[@]} -gt 1 ] ; then
        cmds+=("; pacman -Syy")              # update repos too
        echo "Executing: ${cmds[*]}"
        pkexec bash -c "${cmds[*]}"
    else
        echo "Nothing to do."
    fi

    # cleanup
    rm -rf $tmpdir
}

Main "$@"
